# Generated by Django 5.1.3 on 2024-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mcq_taken',
            field=models.ManyToManyField(blank=True, null=True, to='api.mcq'),
        ),
    ]
